### ISSUE TITLE
SocketCAN example not working

### ISSUE THREAD

**Issue by leodario7** [visionsystemsgmbh/programming_examples#1]
I have followed your README, nonetheless I cannot configure the device as you specified;

`sudo socat pty,link=/dev/netcan0,raw tcp:192.168.0.112:2001&`
`sudo slcand -c -o -s8 /dev/netcan0`
`sudo ip link set up slcan0`

I get : `Cannot find device "slcan0"`.

I'm on Ubuntu 18.04 connected to a NetCANPlus 110 device directly through IP. The device is configured as TCP Raw Server (port 2001) , and DHCP is off and in IP: 192.168.0.112.

**Comment by yegorich** [comment]
Can you see the `/dev/netcan0` device and whether `socat` process is running?

**Comment by yegorich** [comment]
Invoke `socat` like this:

    sudo sh -c "socat pty,link=/dev/netcan0,raw tcp:192.168.0.112:2001&"

**Comment by leodario7** [comment]
Thanks that kinda works, indeed I no longer have the "Cannot find device "slcan0" message, although I still cannot receive any CAN messages, but I also had that problem in Windos with Busmaster. I suppose I must have some configuration wrong.

**Comment by yegorich** [comment]
What is your target CAN bitrate? Have you looked at our [SocketCAN Troubleshooting Guide](http://ftp.vscom.de/multiio/others/info/VSCAN_Manual.pdf#page=87) in the manual?

As to Busmaster, have you used our own [version](http://www.vscom.de/download/multiio/winXP/tools/BUSMASTER_Installer_Ver_3.2.2_VScom_1.0.exe)? Have you checked the filter as described in the manual?

**Comment by leodario7** [comment]
Thanks again, I have looked at the docs, I think the issue must be located somewhere in configuration. Busmaster is your version yes, I do not see any filters in the docs, but yes I set it as it was described, selecting VSCOM CAN API->Advanced and configuring Baud rate at 1Mbit/s (S8), all my tests have been using TCP raw mode on default port 2001. 

Actually I never intended to use SocketCAN I programmed my solution with VSCAN API (C) but I given that I could not receive any of the CAN communication I started trying everything I could (hence why used Busmaster). The example vscandump also didn't work. My suspect is configuration, given that the CAN bus cabling itself can be read with other converters, and I have tried 3 diferent buses.

**Comment by yegorich** [comment]
Let us try another test. Remove all other CAN devices from the CAN cable so that only NetCAN is attached and try a self-test with [vs_can_test_simple.exe](http://ftp.vscom.de/multiio/others/info/VSCAN_Manual.pdf#page=72):

    vs_can_test_simple.exe 192.168.0.112:2001 192.168.0.112:2001

What do CAN Error and Date LEDs say? Do you see CAN Error LED [permanently lighting](http://ftp.vscom.de/multiio/others/info/VSCAN_Manual.pdf#page=28)?

**Comment by leodario7** [comment]
Removing the "CAN Bus" cable, and running the test, prints:

```
DLL version: 1.6.0

SUCCESS: Sending frame from 192.168.0.112:2001 to 192.168.0.112:2001 succeeded.
SUCCESS: Sending frame from 192.168.0.112:2001 to 192.168.0.112:2001 succeeded.
```

The Error Led stays ON, in red (I guess because no cable is connected. Data Led is OFFpermanently. RDY is ON and green, PWR always ON in red, and Wifi off.

**Comment by yegorich** [comment]
But what does the test say, when the cable is attached i.e. without other CAN devices?

**Comment by leodario7** [comment]
Ok, after connecting the CAN Bus, Data Led is flickers in green, and Error is off. The prints are the same, "SUCCESS".

**Comment by leodario7** [comment]
Interestingly, when doing:
`vscandump.exe 192.168.0.112:2001 S1`
Data light turns OFF.
`vscandump.exe 192.168.0.112:2001 S8`
Data light flickers fast. This is expected because the bus is at 1Mbit, what I find interesting, is that it does not print anything in the terminal, both commands produce the same result; It is only in the HW leds that a difference can be observed

**Comment by yegorich** [comment]
That's a good sign when the Data LED is blinking. Because it means, NetCAN receives CAN frames and no filters are set. Where do you invoke `vscandump.exe`? In `cmd.exe` or in any other terminal? I had trouble with [ConEmu](https://conemu.github.io/). It needs extra flushing.

When you now try to read data in BUSMASTER, do you also see Data LED blinking and Error LED off?

**Comment by leodario7** [comment]
I used cmd.exe yes, and with BUSMASTER is indeed the same, when configuring 1Mbit/s, Data LED is blinking, but nothing gets printed. With the initial SocketCan (Ubuntu) question is the same, blinking, no prints. I tried it, because I thought there might be some issue or firewall with Windows, but I got the same behavior.

I also checked that the CAN Bus actually has Data, using a generic USB/CAN converter.

**Comment by yegorich** [comment]
Could you send me the NetCAN configuration as described [here](http://ftp.vscom.de/multiio/others/info/VSCAN_Manual.pdf#page=20). And also the [syslog.txt](http://192.168.0.112/form/syslog.txt) file after you've tried to receive some CAN frames. My e-mail address can be found in my GitHub profile. Thanks.

**Comment by leodario7** [comment]
Thank you very much, I have sent the email with the config file and the syslog.txt attached
