### ISSUE TITLE
vscandump.c not working with latest version of API

### ISSUE THREAD

**Issue by leodario7** [visionsystemsgmbh/programming_examples#2]
I've used the vscandump.c to test the devices, which uses API version 1.10.1 (although the downloaded folder says 1_10_2). When running the executable, nothing is printed, nonetheless, when running the precompiled version using API 1.8.0 or BusMaster app, packets are correctly received. 

For debugging purposes I've changed the Debug flag from NONE to HIGH.

![vscandump](https://user-images.githubusercontent.com/15389025/99969978-7c171380-2d9b-11eb-8fd4-163db73097f0.png)

I was unable to use your CMakeLists.txt configuration, so I assembled my own, is there any special definition that I should take into account?

Additionally I'm using Visual Studio 15 2017 (x64) as compiler. 

**When running more than one client at the same time (two vscandump.exe compiled locally), one of them actually succeds.**

**Comment by leodario7** [comment]
Additionally I've created a simple test program in C++ which emulates vscandump, but for some reasone it gets stuck when setting the bitrate (I've tried 5 and 250000, with the same result). 

```
// std libraries
#include <stdio.h>

#include <array>
#include <atomic>
#include <chrono>
#include <fstream>
#include <iostream>
#include <list>
#include <mutex>
#include <queue>
#include <sstream>
#include <string>
#include <thread>
#include <tuple>
// external libraries
#include <vs_can_api.h>

using std::cout;
using std::endl;
using std::string;

int main() {
  VSCAN_API_VERSION version;
  string idCAN("0000BBC9");
  string maskCAN("FFFF");
  VSCAN_HANDLE handle;
  VSCAN_MSG VSCANmsg;
  DWORD bitrate = 5;

  string ip("192.168.0.152");
  string port_s("2001");
  string address = ip + ":" + port_s;

  cout << "Initialization " << endl;
  if (VSCAN_Ioctl(0, VSCAN_IOCTL_SET_DEBUG_MODE, VSCAN_DEBUG_MODE_CONSOLE) !=
      VSCAN_ERR_OK)
    cout << "VSCAN ERROR at debug mode" << endl;
  if (VSCAN_Ioctl(0, VSCAN_IOCTL_SET_DEBUG, VSCAN_DEBUG_NONE) != VSCAN_ERR_OK)
    cout << "VSCAN ERROR at debug init" << endl;
  if (VSCAN_Ioctl(0, VSCAN_IOCTL_GET_API_VERSION, &version))
    cout << "Failed to get API version" << endl;

  printf("VSCAN-API Version %d.%d.%d\n", version.Major, version.Minor,
         version.SubMinor);
  cout << "Open VSCAN at address: " << address << endl;
  handle = VSCAN_Open(const_cast<char *>(address.c_str()), VSCAN_MODE_NORMAL);
  cout << "Finish Opening " << endl;

  if (VSCAN_Ioctl(handle, VSCAN_IOCTL_SET_BLOCKING_READ, VSCAN_IOCTL_ON) !=
      VSCAN_ERR_OK)
    cout << "VSCAN ERROR at blocking mode" << endl;
  cout << "Blocking read SET" << endl;
  if (VSCAN_Ioctl(handle, VSCAN_IOCTL_SET_SPEED, (void *)bitrate) !=
      VSCAN_ERR_OK)
    cout << "Setting CAN speed failed" << endl;
  cout << "Initialization end" << endl;

  // A mask should be added here
  VSCAN_FILTER filter[1];
  filter[0].Size = 1;
  if (!idCAN.empty() && !maskCAN.empty()) {
    filter[0].Id = stoi(idCAN, nullptr, 16);
    filter[0].Mask = stoi(maskCAN, nullptr, 16);
    cout << "Id used: " << idCAN << " = " << filter[0].Id << endl;
    cout << "Mask used: " << maskCAN << " = " << filter[0].Mask << endl;
  } else {
    cout << "Default mask and Id used" << endl;
    filter[0].Id = 0x0000BBC9;  // Mask DOORS
    filter[0].Mask = 0xFFFF;
  }
  VSCAN_STATUS status;
 // filter ignored
  // if (VSCAN_Ioctl(handle, VSCAN_IOCTL_SET_FILTER, filter) != VSCAN_ERR_OK)
  //   cout << "VSCAN ERROR at masking" << endl;
  // status = VSCAN_Ioctl(handle, VSCAN_IOCTL_SET_FILTER, filter);
  char string_c[33];

  VSCAN_MSG msg;
  DWORD read;
  for (int i = 0; i < 100; i++) {
    status = VSCAN_Read(handle, &msg, 1, &read);
    VSCAN_GetErrorString(status, string_c, 32);
    printf(string_c);
    cout << endl;
    if (msg.Id != 0) {
      cout << "Id:" << std::hex << msg.Id << "\tDATA:";
      for (int j = 0; j < 8; j++) {
        cout << std::hex << +msg.Data[j];  // + because it
                                           // undergoes a promotion to integer
      }
      cout << std::dec << endl;
    }
  }

  VSCAN_Close(handle);
}


```

**Comment by leodario7** [comment]
After several restarts, now it seems to be working, I'm unsure if this might be related with the cmd terminals or some ports left opened by one of the many vscandump.exe which is interrupted by a CTRL+C

Update:

Again not working, restarted network and host pc, nothing, it doesn't even responds to the original vscandump.exe, all of these happened after running my custom program, I guess the devices get stuck in an undefined behavior. Currently the vscandump with flags on High prints the following:

```
+++ vs_can_api.c[181]:           VSCAN_Ioctl(0, 11, 2A0FFA30)
VSCAN-API Version 1.10.1
+++ vs_can_api.c[32]:            VSCAN_Open(192.168.0.152:2001)
+++ sysfuncs.c[629]:             GetDeviceType
+++ sysfuncs_lawicel.c[218]:     ResetDevice_Lawicel
+++ sysfuncs_lawicel.c[39]:      GetDeviceSerialNrNVersion_Lawicel
+++ sysfuncs_lawicel.c[218]:     ResetDevice_Lawicel
+++ vs_can_api.c[181]:           VSCAN_Ioctl(1, 9, 00000001)
+++ vs_can_api.c[181]:           VSCAN_Ioctl(1, 3, 00000005)
+++ sysfuncs_lawicel.c[218]:     ResetDevice_Lawicel
Setting CAN speed failed
+++ vs_can_api.c[122]:           VSCAN_Close(1)
+++ sysfuncs_lawicel.c[218]:     ResetDevice_Lawicel
```

My custom program, also gets stuck setting the speed, and the original (precompiled) vscandump, does not show any error, not even setting speed, but it doesn't received CAN packets anyway.

I'll restart the devices to factory settings.

**Comment by yegorich** [comment]
Our CMake recipe was tested with both Visual Studio 2008 and 2019. Could you post your CMake output?

**Comment by leodario7** [comment]
Hello,

Well everything was related to a mixup in the libraries, I was using 1.10.1 , in some place within my own example, and after that the devices went a bit crazy. After fixing this up, I have had no issues whatsoever. So this issue can be closed. 

As for the CMake files, they are fine, It would be simpler if the repo included the dll and lib, so the linking can be done without invoking CMake-GUI which is needed to provide a path for VS-CAN-API. But again this is just being piky. Also within your files I see you are kinking pthreads, is this necessary, I did some tests and found no problems removing them (variable  ${CMAKE_THREAD_LIBS_INIT}).

**Comment by yegorich** [comment]
Good to know, everything is working as expected.

The problem with the binary library file is that we would have to always update the examples repo when a new API version will be released. We will also have to provide four folders for four library flavours and, with J1939, it would be even more.

You are right. We don't need Threads dependency for the examples. I have removed it.
